### ISSUE TITLE
希望可以更新到12

### ISSUE THREAD

**Issue by liberal7** [BDZNH/MIUI-Theme-Download-Link-Generator#6]

**Comment by BDZNH** [comment]
UWP 版应该是可以用的

**Comment by Heaven7528** [comment]
好的，大佬。非常感谢！

**Comment by Heaven7528** [comment]
UWP版本闪退是为啥呢

**Comment by BDZNH** [comment]
> UWP版本闪退是为啥呢

@Sky-forest   给一下闪退的链接

输入的链接最好是这样的（桌面端浏览器复制出来的链接）
```url
http://zhuti.xiaomi.com/detail/e37873d2-dd21-4149-a42d-e98ec7dd8ed6
```
目前还没有做多余后缀的处理。

**Comment by Heaven7528** [comment]
那像这样的链接（http://zhuti.xiaomi.com/detail/share/86841005-b3cd-4b11-bee9-f5be224eb5a4?miref=share&amp;packId=1119eb91-2b93-4eba-8eca-08fbfa86f5c4）该怎么处理才可以下载呢？还是说得更新软件才可以下载




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BDZNH/MIUI-Theme-Download-Link-Generator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月5日(星期五) 下午2:13
收件人:&nbsp;"BDZNH/MIUI-Theme-Download-Link-Generator"<MIUI-Theme-Download-Link-Generator@noreply.github.com&gt;;
抄送:&nbsp;"何旭升"<1300427193@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [BDZNH/MIUI-Theme-Download-Link-Generator] 希望可以更新到12 (#6)





  
UWP版本闪退是为啥呢
  
@Sky-forest   给一下闪退的链接
 
输入的链接最好是这样的（桌面端浏览器复制出来的链接）
 http://zhuti.xiaomi.com/detail/e37873d2-dd21-4149-a42d-e98ec7dd8ed6  
目前还没有做多余后缀的处理。

**Comment by BDZNH** [comment]
> 那像这样的链接（[http://zhuti.xiaomi.com/detail/share/86841005-b3cd-4b11-bee9-f5be224eb5a4?miref=share&amp;packId=1119eb91-2b93-4eba-8eca-08fbfa86f5c4）该怎么处理才可以下载呢？还是说得更新软件才可以下载](http://zhuti.xiaomi.com/detail/share/86841005-b3cd-4b11-bee9-f5be224eb5a4?miref=share&amp;packId=1119eb91-2b93-4eba-8eca-08fbfa86f5c4%EF%BC%89%E8%AF%A5%E6%80%8E%E4%B9%88%E5%A4%84%E7%90%86%E6%89%8D%E5%8F%AF%E4%BB%A5%E4%B8%8B%E8%BD%BD%E5%91%A2%EF%BC%9F%E8%BF%98%E6%98%AF%E8%AF%B4%E5%BE%97%E6%9B%B4%E6%96%B0%E8%BD%AF%E4%BB%B6%E6%89%8D%E5%8F%AF%E4%BB%A5%E4%B8%8B%E8%BD%BD)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "BDZNH/MIUI-Theme-Download-Link-Generator" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月5日(星期五) 下午2:13 收件人:&nbsp;"BDZNH/MIUI-Theme-Download-Link-Generator"<MIUI-Theme-Download-Link-Generator@noreply.github.com&gt;; 抄送:&nbsp;"何旭升"<1300427193@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [BDZNH/MIUI-Theme-Download-Link-Generator] 希望可以更新到12 (#6) UWP版本闪退是为啥呢 @Sky-forest 给一下闪退的链接 输入的链接最好是这样的（桌面端浏览器复制出来的链接） http://zhuti.xiaomi.com/detail/e37873d2-dd21-4149-a42d-e98ec7dd8ed6 目前还没有做多余后缀的处理。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.


这个是手机上分享出来的？
实际上桌面端浏览器的真正链接应该是
```url
http://zhuti.xiaomi.com/detail/1119eb91-2b93-4eba-8eca-08fbfa86f5c4
```
这个链接应该可以用了。

对分享链接的处理我抽空看看能不能搞定，虽然平日有人反馈崩溃但是没有链接我也看不出来。我是在手机上看主题信息，然后再在网页上搜索出来的。

**Comment by Heaven7528** [comment]
对，这是手机分享出来的链接，那我试试在pc桌面搜索，多谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BDZNH/MIUI-Theme-Download-Link-Generator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月5日(星期五) 下午2:30
收件人:&nbsp;"BDZNH/MIUI-Theme-Download-Link-Generator"<MIUI-Theme-Download-Link-Generator@noreply.github.com&gt;;
抄送:&nbsp;"何旭升"<1300427193@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [BDZNH/MIUI-Theme-Download-Link-Generator] 希望可以更新到12 (#6)





  
那像这样的链接（http://zhuti.xiaomi.com/detail/share/86841005-b3cd-4b11-bee9-f5be224eb5a4?miref=share&amp;packId=1119eb91-2b93-4eba-8eca-08fbfa86f5c4）该怎么处理才可以下载呢？还是说得更新软件才可以下载
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "BDZNH/MIUI-Theme-Download-Link-Generator" <notifications@github.com&gt;; 发送时间:&nbsp;2021年2月5日(星期五) 下午2:13 收件人:&nbsp;"BDZNH/MIUI-Theme-Download-Link-Generator"<MIUI-Theme-Download-Link-Generator@noreply.github.com&gt;; 抄送:&nbsp;"何旭升"<1300427193@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [BDZNH/MIUI-Theme-Download-Link-Generator] 希望可以更新到12 (#6) UWP版本闪退是为啥呢 @Sky-forest 给一下闪退的链接 输入的链接最好是这样的（桌面端浏览器复制出来的链接） http://zhuti.xiaomi.com/detail/e37873d2-dd21-4149-a42d-e98ec7dd8ed6 目前还没有做多余后缀的处理。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
这个是手机上分享出来的？
 实际上桌面端浏览器的真正链接应该是
 http://zhuti.xiaomi.com/detail/1119eb91-2b93-4eba-8eca-08fbfa86f5c4  
这个链接应该可以用了。
 
对分享链接的处理我抽空看看能不能搞定，虽然平日有人反馈崩溃但是没有链接我也看不出来。我是在手机上看主题信息，然后再在网页上搜索出来的。
